title: "The Database"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "Setting up the database on the server"
  video: "http://www.youtube.com/watch?v=C-JJeXbZDZM"
  cover: 'assets/postgresql.png'
  color: "sun-flower"