title: "Setting up Shopper"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "Setting up the Shopper App"
  video: "http://www.youtube.com/watch?v=8nsbbwdfv0A"
  cover: 'assets/shopper-02.png'
  color: "wisteria"