title: "Understanding the Stack"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  blurb: "Understanding our stack"
  video: "http://www.youtube.com/watch?v=c64KWbwealU"
  cover: 'assets/stack.png'
  color: "belize-hole"