title: "Analytics with Redis Part 3"
tags: ["Redis", "Ruby", "Nosql", "Rails"]
playlists: ["A Shot of Ruby"]
publish: false
details:
  blurb: "We're going to apply what we've learned about redis in our Rails app"
  cover: "assets/cover.png"
  color: "pomegranate"