title: "Introduction to DevOps for Developers"
tags: ["DevOps"]
playlists: ["DevOps for Developers"]
publish: true
details:
  cover: "assets/intro.png"
  blurb: "Introducing DevOps for Developers"
  video: "http://www.youtube.com/watch?v=xr5bZ2ZR28w"
  color: "orange"