title: "Analytics with Redis Part 1"
tags: ["Redis", "Ruby", "Nosql"]
playlists: ["A Shot of Ruby"]
publish: true
details:
  blurb: "How to build a basic analytics system with Redis."
  cover: "assets/redis-01.png"
  video: "http://www.youtube.com/watch?v=X6OnNLtJq_Q"
  color: "pomegranate"